name: GinaErickson
favicon: null
layout_spectrum: 0.25931
typography_spectrum: 0.50517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b6b6b6'
    - '#777777'
    - '#fcd201'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
